title: DSC MA4
description: Huize's DSC Capstone Program MA4 @ UC San Diego
tagline: Landing page for the Huize's MA4.
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://dsc-ma4-huize.org' # the base hostname & protocol for your site, e.g. http://example.com
author: Huize Mao
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

theme: minima

# Build settings
markdown: kramdown
permalink: pretty

# Safe plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
