title: DSC MA4
description: Huize's DSC Capstone Program MA4 @ UC San Diego
tagline: Landing page for the Huize's MA4.
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://dsc-ma4-huize.org' # the base hostname & protocol for your site, e.g. http://example.com
author: Suraj Rampure
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: bluecsd
search_enabled: true
heading_anchors: true
permalink: pretty
footer_content: